name: Fullstack CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:

  java-build:
    name: Java Backend Build
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
    
      - name: Build Java backend
        working-directory: java-backend
        run: mvn clean package -DskipTests

      - name: Build Java Docker Image 
        working-directory: java-backend
        run: docker build -t java-backend:latest -t java-backend:${{ github.run_number }} -t java-backend:${{ github.sha }} .

  python-check:
    name: Python Service Check
    runs-on: self-hosted
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
    
      - name: Install dependencies
        working-directory: python-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Basic import test
        working-directory: python-service
        run: python -c "import app; print('Python service OK')"

      - name: Build Python Docker Image 
        working-directory: python-service
        run: docker build -t python-service:latest -t python-service:${{ github.run_number }} -t python-service:${{ github.sha }} .
        
  k3d-deploy:
    name: Deploy to k3d Cluster
    runs-on: self-hosted

    needs: [java-build, python-check]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if k3d cluster exists
        run: |
          if k3d cluster list | grep -q "fullstack-app"; then
            echo "Cluster exists"
          else
            echo "Cluster fullstack-app doesn't exist"
            exit 1
          fi

      - name: Set kubeconfig
        run: |
          export KUBECONFIG=$(k3d kubeconfig write fullstack-app)
          echo "KUBECONFIG set"

      - name: Verify cluster
        run: kubectl get nodes
        
